### ISSUE TITLE
starter page before login

### ISSUE THREAD

**Issue by michellejanay** [ChidimmaOfodum/WM4--Final-Project--SlackDash#27]
As a user,
I want to see the option to login or signup
So that I can either create and account or login to my account

New design????

**Comment by rgc-hdlr** [comment]
https://www.canva.com/design/DAFaZtJ3yjk/kAvi7Fyr1juPUZeETioLbg/edit

**Comment by rgc-hdlr** [comment]
We should think about adding a headline telling users what the purpose of our application is
